services:

  nginx_webdav:
    build:
      context: .
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    ports:
      - "${PORT}:80"
    volumes:
      - ${MEDIA_PATH}:/media/data:ro
    environment:
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
    restart: unless-stopped
